name: service_squad
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0-210.2.beta <4.0.0'

dependencies:
  cloud_firestore: ^4.9.3
  date_format: any
  firebase_auth: 4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.2.8
  firebase_ui_auth: ^1.9.0
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  pdf: ^3.10.4
  intl: any
  #  firebase_ui_oauth_google: ^1.2.12
  image_picker: ^1.0.4
  firebase_messaging: ^14.6.9
  uuid: ^4.2.1
  flutter_rating_bar: ^4.0.1
  flutter_stripe: ^9.5.0+1
  http: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/1.png
    - assets/house_keeping.jpeg
    - assets/snow_clearance.jpeg
    - assets/lawn_mowing.jpeg
    - assets/handy.jpeg
